### PR TITLE
Limit rss feed to posts from last month and allow tag-based filtering

### PR DESCRIPTION
**Pull request by PtrTn**
Implementation of issue #80, which limits the rss feed to posts from last month only.
Additionally allow filtering based on one or multiple tags.

### CODE REVIEW

**Comment by PtrTn** [comment]
@brendt in #80 your example url contained examples like `/rss?topic=php`.
That implied `php` is a `topic`, but in fact it's a `tag`.
So I've taken the liberty to implement urls like  `/rss?tag=php` instead.

Let me know if that's alright

**Comment by brendt** [comment]
Hi @PtrTn 

Thanks for the PR! I'm sorry I wan't able to get back at you sooner, but there were some personal issues IRL that had to be taken care of :) I'll merge this PR into develop, do some more testing over there and I'll then merge it into master later this week :)

**Comment by PtrTn** [comment]
Hey @brendt, 
I understand personal stuff comes first, no problem. Good to see the PR getting merged. Feel free to let me know if there's any findings, I'd be happy to solve them.

**Comment by brendt** [comment]
Thanks again for the PR, it's deployed now! I made some minor changes to allow a more flexible query parameter filter: 

- https://github.com/brendt/aggregate.stitcher.io/commit/878f2027e6daaa54310a66a6f78b51bc682996bb 
- https://github.com/brendt/aggregate.stitcher.io/commit/a3c05a734730dd389adf4c9c0cc4bb831d4a27d6

And also fixed a bug:
- https://github.com/brendt/aggregate.stitcher.io/commit/7399d512b674024624c044721e4edcacdb1cd3a0

Thanks again!

**Pull request merged**
